sportx:
  global: local>application2



feign:
  client:
    config:
      default:
        connectTimeout: 10
        readTimeout: 60
        loggerLevel: full
  logger:
    audit:
      loggerLevel: full
    store:
      loggerLevel: full
