sportx:
  global: local>application2



feign:
  client:
    config:
      default:
        connectTimeout: 1000000
        readTimeout: 6000000
        loggerLevel: FULL
  logger:
    audit:
      loggerLevel: FULL
    store:
      loggerLevel: FULL

  loggerLevel: FULL
  connectTimeoutMillis: 10000000
  readTimeoutMillis: 10000000

  
