sportx:
  global: local>application2



feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 600000
        loggerLevel: FULL
  logger:
    audit:
      loggerLevel: FULL
    store:
      loggerLevel: FULL
