spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/audit
    username: audit
    password: audit
    driverClassName: org.mariadb.jdbc.Driver
    max-active: 100
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-test-query: SELECT 1
      data-source-properties:
        connectTimeout: 300
        socketTimeout: 300

  #flyway:
  #  schemas: audit
  #  baseline-on-migrate: false
  #  validate-on-migrate: true
  #  table: schema_version

server:
  port: 6060
management:
  server:
    port: 6061

sportx:
  global: local>application>audit

